
### ADMIN LOGIN
POST https://atp-24eg105b40.onrender.com/common-api/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"admin"
}

### CHANGE PASSWORD
### READ ALL USERS AND AUTHORS (ONLY EMAILS)
GET https://atp-24eg105b40.onrender.com/admin-api/users

### BLOCK OR ACTIVATE USER OR AUTHOR
PATCH https://atp-24eg105b40.onrender.com/admin-api/user-status
Content-Type: application/json

{
    "email":"prasanna@gmail.com",
    "isUserActive":false
}