###Register user
POST https://atp-24eg105b40.onrender.com/auth/register
Content-Type: application/json

{
    "firstName":"user2",
    "lastName":"user2",
    "email":"user2@example.com",
    "role":"USER",
    "password":"user2",
    "profileImageUrl":"https://example.com/avatars/default.png"
}

###User login
POST https://atp-24eg105b40.onrender.com/auth/login
Content-Type: application/json

{
    "email":"user1@example.com",
    "password":"user1"
}

###USER LOGOUT(here post is not return bcoz we are not sending any data to backend we are just clearing the cookie in frontend)
GET  https://atp-24eg105b40.onrender.com/auth/logout

###READ ARTICLES OF ALL AUTHORS
GET https://atp-24eg105b40.onrender.com/user-api/article
###ADD COMMENT BY USER TO AN ARTICLE
PUT https://atp-24eg105b40.onrender.com/user-api/article
Content-Type: application/json

{

    "articleId":"69b4d8852847b4d861c79524",
    "comment":"This is a useful article!"
}

###CHANGE PASSWORD
PUT https://atp-24eg105b40.onrender.com/auth/password
Content-Type: application/json

{
    "currentPassword": "user1",
    "newPassword": "User1"
}